- hosts: webservers
  gather_facts: False
  become: yes
  vars:
    group_name: flask
    user1: flask

  tasks:
    - name: Create group
      group:  
        name: "{{ group_name }}"
        state: present
      

    - name: Add the user with a specific uid and a primary group
      user:
        name: "{{ user1 }}"
        comment: "{{ user1 }}"
        group: "{{ group_name }}"
        shell: /bin/bash
        home: /home/{{ user1 }}
        create_home: yes

    - name: Adding pub key for '{{ user1 }}'
      authorized_key:
        user: "{{ user1 }}"
        key: "{{ item }}"
      with_file:
        - /var/lib/jenkins/.ssh/flask_id_rsa.pub

    - name: Run "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Install apache service but avoid starting it immediately
      apt: name=apache2 state=present
      environment:
        RUNLEVLEL: 1

    - name: Install the package "python-pip"
      apt:
        name: python-pip
        state: present

    - name: Install the package "libapache2-mod-wsgi"
      apt:
        name: libapache2-mod-wsgi
        state: present

    - name: Install Flask using pip
      pip:
        name: Flask
        version: 1.0.2

    - name: Install pytest using pip
      pip:
        name: pytest

    - name: Install coverage using pip
      pip:
        name: coverage

    - name: Create Flask app parent directory
      file:
        path: /var/www/flask
        state: directory
        owner: "{{ user1 }}"
        group: "{{ group_name }}"
        mode: 0777